version: '3.8'

services:
  webapi:
    image: cleanarchitecture-webapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - UseInMemoryDatabase=true
    restart: always
